### ISSUE TITLE
Citation for TLRU scheme

### ISSUE THREAD

**Issue by mbilal084** [jahnestacado/tlru#1]
Thank you for implementing the TLRU scheme. It is always better to give credit to those who first publish an idea. We are the first who come up with this idea and published a research article. Please cite the following article in your about section. Thank you.
M. Bilal and S. Kang, "Time Aware Least Recent Used (TLRU) cache management policy in ICN," 16th International Conference on Advanced Communication Technology, 2014, pp. 528-532, doi: 10.1109/ICACT.2014.6779016.

**Comment by jahnestacado** [comment]
Since this tlru implementation is not really based on your paper, I  put a reference to the wikipedia page where the main concept of TLRU is described and your paper is also referenced.

https://github.com/jahnestacado/tlru/commit/ca13a467d7f1ae27be35ba4a241ad8155ad19dd3

**Comment by mbilal084** [comment]
That Wikipedia entry is by me, and it also refers to my article. Wikipedia is for information sharing, but you need to check the real sources from reference. 
Please check the reference list on Wikipedia and cite my article.
