### ISSUE TITLE
the eviction policies should suppose timestamp when the space is full

### ISSUE THREAD

**Issue by kc-co9** [jahnestacado/tlru#3]
you can see the page about tlru apply in icn

**Comment by jahnestacado** [comment]
@kcl-co It is difficult to take this type of tickets seriously. Please provide some context about your proposal along with a use case.

**Comment by kc-co9** [comment]
@jahnestacado i think of the TLRU created from [《Time Aware Least Recent Used (TLRU) Cache Management Policy in ICN》](https://arxiv.org/pdf/1801.00390.pdf)，which describes the Algorithm-(TLRU) like this:

```
4.  if TTU > Ti
5.      if s[i]>=n
6.          Do V ci E s[i]
7.              if TTU! < t -> ci E Ev[i]
8.                 LRU(Ev[i]) -> Evict
9.                 s[i] -> Ci U s[i]
10.             else
11.                LRU(s[i]) -> Evict
12.                s[i] -> ci U s[i]
13.     else s[i] - ci U s[i]
14. else Reject
```

the pseudo-code maybe have some bad, more detail you can lookup the 《Time Aware Least Recent Used (TLRU) Cache Management Policy in ICN》.

**Comment by kc-co9** [comment]
in the pseudo code, the 'T' or 't' represent that average request time, and the 'Ev' is computed by ttu and  average request time. at the paper it is not explicit to show the  'Ev' computation concrete code, but describes the thinking. if we dont think of the average request time, the code will be :
```
5.      if s[i]>=n
6.          Do V ci E s[i]
11.                LRU(s[i]) -> Evict
12.                s[i] -> ci U s[i]
13.     else s[i] - ci U s[i]
```
but i think it is boring, because it is a common lru replacement algorithm.

**Comment by kc-co9** [comment]
maybe just a common lru, but it will check the ttu while invoking 'put' or 'get' method, i dont know.

**Comment by jahnestacado** [comment]
This repo is an implementation of a cache that supports 2 custom eviction strategies that were not based on any specific paper.
I don't see how referring to other work will dictate how my code should work because the design requirements are different.
I would suggest to have a look at the README first and then try to understand the code. Closing this as it's not rellevant.
